name: "Cube"
locales: [en]
seo_title: Cube &mdash; Free Website Template, Free HTML5 Template by FreeHTML5.co
meta_keywords: "free website templates, free html5, free template, free bootstrap, free website template, html5, css3, mobile first, responsive"
meta_description: "Free HTML5 Website Template by FreeHTML5.co"
metafields:
  address:
    company: Company
    street: 700 South Laflin Street
    city: City, AA 99999
    country: Country
    gmap: https://www.google.com/maps/embed/v1/place?key=AIzaSyA0Dx_boXQiwvdz8sJHoYeZNVTdoWONYkU&q=place_id:ChIJn6wOs6lZwokRLKy1iqRcoKw
  contacts:
    phone: "+1 (0) 000 0000 001"
    days: Monday to Friday
    hours: '09h00 – 20h00'
  emails:
    info: info@site.com
    support: support@site.com
  networks:
    facebook: azer
    twitter: azer
